### ISSUE TITLE
symlink-manager does not work and throw error.

### ISSUE THREAD

**Issue by graphicsxp** [mehmet-erim/symlink-manager#7]
When I run symlink --angular, after choosing my library from the menu, it runs and fails with this error. It shows "Processing..." forever until I kill the process.

However creating the symlink by hand (`npm link` from dist folder and then `npm link` from root folder) works just fine.

.(node:17308) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: npm link
npm ERR! code E404
npm ERR! 404 Not Found - GET https://my-private-feed/_packaging/npm-feed/npm/registry/tslib - NotFound
npm ERR! 404
npm ERR! 404  'tslib@^2.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'breeze-helpers'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\berthesa\AppData\Roaming\npm-cache\_logs\2020-12-02T18_46_32_529Z-debug.log
    at makeError (C:\Users\berthesa\AppData\Roaming\npm\node_modules\symlink-manager\node_modules\execa\lib\error.js:59:11)
    at Proxy.module.exports.sync (C:\Users\berthesa\AppData\Roaming\npm\node_modules\symlink-manager\node_modules\execa\index.js:188:17)
    at C:\Users\berthesa\AppData\Roaming\npm\node_modules\symlink-manager\src\angular.js:124:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:17308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting 
a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17308) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mehmet-erim** [comment]
Hi @graphicsxp 

Some problems may arise in linking. This situation may vary depending on whether it is macOS, Linux, or Windows. Have you tried the copy command? I always use it. 

Please try command below instead of linking:

```
symlink copy --angular --sync --all-packages
```
